apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    course: devops
    trainer: "shiva"
  annotations:
    com.roboshop.training.durations: "120 hours"
    jenkins.url: "https://jenkins.com/roboshop/catalogue#456"

spec:
  #list of containers
  containers:
  - name: hello-pod
    image: nginx
    ports:
    - containerPort: 80